databases:
  - name: crossword-db
    plan: free
    databaseName: crossword
    user: crossword

services:
  - type: web
    plan: free
    name: crossword
    runtime: node
    buildCommand: pip install -r requirements.txt && npm install
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crossword-db
          property: connectionString
      - key: TZ
        value: America/New_York
